version: '3.1'

services:
  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
    volumes:
      - /Applications/dockers/zhiwei/logs/nginx:/var/log/nginx
      - /Applications/dockers/zhiwei/www:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - zhiweinet

  php-fpm:
    build: ./services/php
    volumes:
      - /Applications/dockers/zhiwei/www:/var/www/html
    expose:
      - 9000
    depends_on:
      - dbmysql
    networks:
      - zhiweinet

  dbmysql:
    build: ./services/mysql
    volumes:
      - /Applications/dockers/zhiwei/data/mysql:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - zhiweinet

networks:
  zhiweinet: